ONSdigital/the-train

src/main/java/com/github/davidcarboni/thetrain/api/Commit.java, src/main/java/com/github/davidcarboni/thetrain/api/CommitManifest.java, src/main/java/com/github/davidcarboni/thetrain/helpers/Configuration.java, src/main/java/com/github/davidcarboni/thetrain/storage/Transactions.java, src/main/java/com/github/davidcarboni/thetrain/storage/Website.java, src/test/java/com/github/davidcarboni/thetrain/Generator.java
Support two new environment variables for compatibility (`WEBSITE` and `TRANSACTION_STORE` instead of `thetrain.website` and `thetrain.transactions`)
Legacy values (using `-D` and environment variables) are still supported.
* Run the tests
* Change config using environment variables when starting app
@LloydGriffiths @daiLlew
=> support proper environment variables, but still allow legacy

the-train.nomad
* Set the min heap size in nomad plan so we will fail fast if we are out of memory and to reduce wasted time resizing the heap
* Configure the healthy threshold and deadline
* Enable auto rollback on failed deploy
* Increase the stagger time to allow enough time for scheduling
Ensure configurations are valid and logical.
Anyone but me.
=> Improve nomad plan

the-train.nomad
Fix copy paste error in nomad plan
Check the correct variable is used.
Anyone but me.
=> Fix copy paste error in nomad plan

the-train.nomad
Allow for splitting the nomad classes.
Ensure the nomad class constraints are correct.
Anyone but me.
=> Allow for splitting the nomad classes

the-train.nomad
Updates to nomad plan to be merged into cmd
Check for conflicts
Anyone
=> Merge develop into cmd-develop

src/main/java/com/github/davidcarboni/thetrain/api/Begin.java, src/main/java/com/github/davidcarboni/thetrain/api/Commit.java, src/main/java/com/github/davidcarboni/thetrain/api/CommitManifest.java, src/main/java/com/github/davidcarboni/thetrain/api/Publish.java, src/main/java/com/github/davidcarboni/thetrain/api/Rollback.java, src/main/java/com/github/davidcarboni/thetrain/api/Transaction.java, src/main/java/com/github/davidcarboni/thetrain/api/common/Endpoint.java, src/main/java/com/github/davidcarboni/thetrain/helpers/Configuration.java, src/main/java/com/github/davidcarboni/thetrain/helpers/PathUtils.java, src/main/java/com/github/davidcarboni/thetrain/json/Transaction.java, src/main/java/com/github/davidcarboni/thetrain/json/UriInfo.java, src/main/java/com/github/davidcarboni/thetrain/service/TransactionsService.java, src/main/java/com/github/davidcarboni/thetrain/service/TransactionsServiceImpl.java, src/main/java/com/github/davidcarboni/thetrain/storage/Publisher.java, src/main/java/com/github/davidcarboni/thetrain/storage/Transactions.java, src/main/java/com/github/davidcarboni/thetrain/storage/Website.java, src/test/java/com/github/davidcarboni/thetrain/Generator.java, src/test/java/com/github/davidcarboni/thetrain/api/AbstractAPITest.java, src/test/java/com/github/davidcarboni/thetrain/api/BeginTest.java, src/test/java/com/github/davidcarboni/thetrain/api/CommitTest.java, src/test/java/com/github/davidcarboni/thetrain/api/RollbackTest.java, src/test/java/com/github/davidcarboni/thetrain/api/TransactionTest.java, src/test/java/com/github/davidcarboni/thetrain/json/UriInfoTest.java, src/test/java/com/github/davidcarboni/thetrain/storage/PublisherTest.java, src/test/java/com/github/davidcarboni/thetrain/storage/TransactionsTest.java, the-train.nomad
Remove pointless encryption from The-Train
Run the stack locally, publish a collection, content should be published
Requires `feature/remove-train-encryption-2` branch of zebedee
Anyone except @ian-kent
=> Remove pointless encryption from The-Train

src/main/java/com/github/davidcarboni/thetrain/api/Begin.java, src/main/java/com/github/davidcarboni/thetrain/api/Commit.java, src/main/java/com/github/davidcarboni/thetrain/api/CommitManifest.java, src/main/java/com/github/davidcarboni/thetrain/api/Publish.java, src/main/java/com/github/davidcarboni/thetrain/api/Rollback.java, src/main/java/com/github/davidcarboni/thetrain/api/Transaction.java, src/main/java/com/github/davidcarboni/thetrain/api/common/Endpoint.java, src/main/java/com/github/davidcarboni/thetrain/helpers/Configuration.java, src/main/java/com/github/davidcarboni/thetrain/helpers/PathUtils.java, src/main/java/com/github/davidcarboni/thetrain/json/Transaction.java, src/main/java/com/github/davidcarboni/thetrain/json/UriInfo.java, src/main/java/com/github/davidcarboni/thetrain/service/TransactionsService.java, src/main/java/com/github/davidcarboni/thetrain/service/TransactionsServiceImpl.java, src/main/java/com/github/davidcarboni/thetrain/storage/Publisher.java, src/main/java/com/github/davidcarboni/thetrain/storage/Transactions.java, src/main/java/com/github/davidcarboni/thetrain/storage/Website.java, src/test/java/com/github/davidcarboni/thetrain/Generator.java, src/test/java/com/github/davidcarboni/thetrain/api/AbstractAPITest.java, src/test/java/com/github/davidcarboni/thetrain/api/BeginTest.java, src/test/java/com/github/davidcarboni/thetrain/api/CommitTest.java, src/test/java/com/github/davidcarboni/thetrain/api/RollbackTest.java, src/test/java/com/github/davidcarboni/thetrain/api/TransactionTest.java, src/test/java/com/github/davidcarboni/thetrain/json/UriInfoTest.java, src/test/java/com/github/davidcarboni/thetrain/storage/PublisherTest.java, src/test/java/com/github/davidcarboni/thetrain/storage/TransactionsTest.java, the-train.nomad
Don't encrypt content being sent to The Train
Deployed to develop - check publishing still works
Anyone except @ian-kent
=> Remove train encryption

the-train.nomad
Restrict deployment to only mount instances to explicitly limit deployment to instances with the content volume.
Ensure the node pattern only matches the mount nodes.
Anyone but me.
=> Restrict deployment to mount instances

README.md
=> kick off build

src/main/java/com/github/davidcarboni/thetrain/helpers/UnionInputStream.java, src/main/java/com/github/davidcarboni/thetrain/storage/Publisher.java
more logging to help debug issue in dev env.
=> added more logging to debug issues in dev env

src/main/java/com/github/davidcarboni/thetrain/helpers/UnionInputStream.java, src/main/java/com/github/davidcarboni/thetrain/storage/Publisher.java
=> more logging to debug issue

src/main/java/com/github/davidcarboni/thetrain/storage/Publisher.java
=> hack hack hack fingers crossed

pom.xml
Updated dp-logging version to lastest.
=> pin dp-logging version

src/main/java/com/github/onsdigital/thetrain/App.java
Hotfix - disable pretty logging in prod.
=> disabled pretty logging

src/main/java/com/github/onsdigital/thetrain/App.java
Added missing exception to log event and updated exit code to use appropriate value.
=> added missing exception and used appropriate exit code

src/main/java/com/github/onsdigital/thetrain/exception/handler/PublishExceptionHandler.java
Update publish exception handler logging to log cause if it exists.
=> improvements to publish exception logging

src/main/java/com/github/onsdigital/thetrain/exception/handler/PublishExceptionHandler.java
minor tweek to exception logging
=> minor tweek to exception logging to debug issue

pom.xml
Update `dp-logger` version to `release.1.3.0`
=> updated logger version

pom.xml, src/main/java/com/github/onsdigital/thetrain/filters/AfterFilter.java, src/main/java/com/github/onsdigital/thetrain/filters/BeforeFilter.java
Updated to the latest version of - 1.6.0 - of `dp-logger`. Includes fix for incorrect trace ID's
=> updated to latest latest version of the logger

pom.xml
Updated jackson-databind dependency
Ensure service builds and runs successfully.
Run `make audit` and ensure there are no critical `jackson-databind` vulnerabilities detected.
Anyone but me.
=> Update jackson-databind dependency

Makefile, src/main/java/com/github/onsdigital/thetrain/configuration/AppConfiguration.java
- Updated app configuration with new config values required for fix (will be used in next PR).
- Updated `Makefile` to set defaults.
PR.
Anyone.
=> added new app config values and updated makefile

README.md, src/main/java/com/github/onsdigital/thetrain/configuration/AppConfiguration.java
Updated ReadMe with latest instructions.
Read the read me...
Anyone.
=> Updated read me

Dockerfile.concourse, pom.xml
Changed docker base image to openjdk:8-jre
Check that docker image tag is appropriate
Anyone but me
=> Change docker base image to openjdk:8-jre

pom.xml
* new dp-logging released version update
* new dp-logging released version - v2.0.0-beta
* anyone not me
=> New dp-logging library update

pom.xml
Bump `spring-test` to latest version so to remove security vulnerabilities flagged by the audit job. `5.3.8` => `5.3.19`
Sense check.
Anyone
=> Release 2.8.1

pom.xml
Upgrade dependencies to remove vulnerabilities flagged by audit job
Check changes make sense and audit passes
Anyone
=> Remove vulnerabilities

pom.xml
Upgrade dependencies to remove vulnerabilities
👀 
Anyone
=> Release 2.8.2

pom.xml, src/test/java/com/github/onsdigital/thetrain/helpers/ShaOutputStreamTest.java
Updated external and internal dependencies to latest minor version.
Be sure you have java 1.8 as the current jdk and maven is using it (`mvn --version`)
if so you can run:  `mvn clean package` 
No  errors should appear, the build should run ok and the test cases should run ok
`mvn versions:display-dependency-updates -DallowMajorUpdates=false`
No libraries should be mentioned here that need updating
run the app:
- set environment first
export zebedee_root=/<your_zebedee_content_root>/website/zebedee-content/generated
export MAX_FILE_UPLOAD_SIZE_MB=10
export MAX_REQUEST_SIZE_MB=1
export FILE_THRESHOLD_SIZE_MB=2 
execute ./run.sh
...the train should be running on localhost port 8084
execute. url -X POST http://localhost:8084/begin | jq '.'
... If successful you should see a response similar …
=> update dependencies in pom

pom.xml, src/test/java/com/github/onsdigital/thetrain/helpers/ShaOutputStreamTest.java
- update internal and external dependencies
Sense check
Anyone
=> update internal and external dependencies

the-train.nomad
As per title.
No ONS libs have been updated.
Ensure changes are similar to whats in babbage for 'spread'.
Anyone.
=> Ensure deployments spread over availability zones

the-train.nomad
As per title.
Visual inspection.
Anyone.
=> Use distinct_hosts in nomad plan

.github/CODEOWNERS, pom.xml
Added CODEOWNERS file as per ONS standards
=> Add CODEOWNERS file

Dockerfile, Dockerfile.concourse, ci/audit.yml, ci/build.yml, ci/unit.yml
switch from openJDK to temurin
Check is ok and tests pass
Anyone
=> switch from openJDK to temurin

src/main/java/com/github/onsdigital/thetrain/App.java, the-train.nomad
* Add a basic health check endpoint (#128 )
=> Release 2.12.0

pom.xml
Upgraded jetty due to audit failure. 
Check looks ok. 
Not me.
=> Upgrade jetty
